apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: lab4-front
  labels: 
    app: lab4-front  
spec: 
  replicas: 2
  selector: 
    matchLabels: 
      app: lab4-front  
  template: 
    metadata: 
      labels: 
        app: lab4-front   
    spec: 
      containers: 
      - name: lab4-front  
        image: "ifilyaninitmo/itdt-contained-frontend:master" 
        env: 
        - name: REACT_APP_USERNAME 
          value: "zxc zxc" 
        - name: REACT_APP_COMPANY_NAME 
          value: "привтет на русском (russian words)" 
        ports: 
        - containerPort: 3000