apiVersion: crd.projectcalico.org/v1
kind: IPPool
metadata:
   name: ippool-west
spec:
   cidr: 10.1.1.0/24
   ipipMode: Always
   natOutgoing: true
   nodeSelector: zone == "west"
---

apiVersion: crd.projectcalico.org/v1
kind: IPPool
metadata:
   name: ippool-east
spec:
   cidr: 10.1.2.0/24
   ipipMode: Always
   natOutgoing: true
   nodeSelector: zone == "east"