apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: lab3-ingress
spec:
 rules:
   - host: lab3-frontend.org
     http:
       paths:
         - backend:
             service:
               name: lab3-front
               port:
                 number: 3000
           path: /
           pathType: Prefix
 tls:
   - hosts:
       - lab3-frontend.org
     secretName: lab3-secret